@echo off
echo Starting Clario Full Application...
echo.
echo Starting Backend...
start "Clario Backend" cmd /k "cd backend && python -m venv venv && call venv\Scripts\activate && pip install -r requirements.txt && python main.py"
echo.
echo Waiting 5 seconds for backend to start...
timeout /t 5 /nobreak > nul
echo.
echo Starting Frontend...
start "Clario Frontend" cmd /k "cd frontend && npm install && npm start"
echo.
echo Both services are starting...
echo Backend will be available at: http://localhost:8000
echo Frontend will be available at: http://localhost:3000
pause
